Account:
  - AccountAttachPaymentMethod
  - AccountBillingGroupList
  - AccountCreate
  - AccountDelete
  - AccountEventList
  - AccountGet
  - AccountList
  - AccountMove
  - AccountPaymentMethodDelete
  - AccountPaymentMethodsList
  - AccountProjectsList
  - AccountProjectsTeamsList
  - AccountUpdate
  - AccountUserProjectsList
  - AccountUserTeamsList
  - AccountUsersSearch
AccountAuthentication:
  - AccountAuthenticationMethodCreate
  - AccountAuthenticationMethodDelete
  - AccountAuthenticationMethodGet
  - AccountAuthenticationMethodUpdate
  - AccountAuthenticationMethodsList
AccountTeam:
  - AccountTeamCreate
  - AccountTeamDelete
  - AccountTeamGet
  - AccountTeamInvitesList
  - AccountTeamList
  - AccountTeamProjectAssociate
  - AccountTeamProjectAssociationUpdate
  - AccountTeamProjectDisassociate
  - AccountTeamProjectList
  - AccountTeamUpdate
AccountTeamMember:
  - AccountTeamMemberCancelInvite
  - AccountTeamMemberVerifyInvite
  - AccountTeamMembersDelete
  - AccountTeamMembersInvite
  - AccountTeamMembersList
AlloyDBOmni:
  - AlloyDbOmniGoogleCloudPrivateKeyIdentify
  - AlloyDbOmniGoogleCloudPrivateKeyRemove
  - AlloyDbOmniGoogleCloudPrivateKeySet
ApplicationUser:
  - ApplicationUserAccessTokenCreate
  - ApplicationUserAccessTokenDelete
  - ApplicationUserAccessTokensList
  - ApplicationUserCreate
  - ApplicationUserDelete
  - ApplicationUserGet
  - ApplicationUserUpdate
  - ApplicationUsersList
BillingGroup:
  - BillingGroupCreate
  - BillingGroupCreditsClaim
  - BillingGroupCreditsList
  - BillingGroupDelete
  - BillingGroupEventList
  - BillingGroupGet
  - BillingGroupInvoiceCsvGet
  - BillingGroupInvoiceDownload
  - BillingGroupInvoiceLinesList
  - BillingGroupInvoiceList
  - BillingGroupList
  - BillingGroupProjectAssign
  - BillingGroupProjectList
  - BillingGroupProjectsAssign
  - BillingGroupUpdate
ClickHouse:
  - ServiceClickHouseCurrentQueries
  - ServiceClickHouseDatabaseCreate
  - ServiceClickHouseDatabaseDelete
  - ServiceClickHouseDatabaseList
  - ServiceClickHouseQuery
  - ServiceClickHouseQueryStats
  - ServiceClickHouseTieredStorageSummary
Cloud:
  - ListClouds
  - ListProjectClouds
Domain:
  - OrganizationDomainAdd
  - OrganizationDomainUpdate
  - OrganizationDomainVerify
  - OrganizationDomainsList
  - OrganizationDomainsRemove
Flink:
  - ServiceFlinkOverview
FlinkApplication:
  - ServiceFlinkCreateApplication
  - ServiceFlinkDeleteApplication
  - ServiceFlinkGetApplication
  - ServiceFlinkListApplications
  - ServiceFlinkUpdateApplication
FlinkApplicationDeployment:
  - ServiceFlinkCancelApplicationDeployment
  - ServiceFlinkCreateApplicationDeployment
  - ServiceFlinkDeleteApplicationDeployment
  - ServiceFlinkGetApplicationDeployment
  - ServiceFlinkListApplicationDeployments
  - ServiceFlinkStopApplicationDeployment
FlinkApplicationVersion:
  - ServiceFlinkCreateApplicationVersion
  - ServiceFlinkDeleteApplicationVersion
  - ServiceFlinkGetApplicationVersion
  - ServiceFlinkValidateApplicationVersion
FlinkJob:
  - ServiceFlinkJobDetails
  - ServiceFlinkJobsList
Kafka:
  - ServiceKafkaAclAdd
  - ServiceKafkaAclDelete
  - ServiceKafkaAclList
  - ServiceKafkaNativeAclAdd
  - ServiceKafkaNativeAclDelete
  - ServiceKafkaNativeAclGet
  - ServiceKafkaNativeAclList
  - ServiceKafkaQuotaCreate
  - ServiceKafkaQuotaDelete
  - ServiceKafkaQuotaDescribe
  - ServiceKafkaQuotaList
  - ServiceKafkaTieredStorageStorageUsageByTopic
  - ServiceKafkaTieredStorageStorageUsageTotal
  - ServiceKafkaTieredStorageSummary
KafkaConnect:
  - ServiceKafkaConnectCreateConnector
  - ServiceKafkaConnectDeleteConnector
  - ServiceKafkaConnectEditConnector
  - ServiceKafkaConnectGetAvailableConnectors
  - ServiceKafkaConnectGetConnectorConfiguration
  - ServiceKafkaConnectGetConnectorStatus
  - ServiceKafkaConnectList
  - ServiceKafkaConnectPauseConnector
  - ServiceKafkaConnectRestartConnector
  - ServiceKafkaConnectRestartConnectorTask
  - ServiceKafkaConnectResumeConnector
KafkaMirrorMaker:
  - ServiceKafkaMirrorMakerCreateReplicationFlow
  - ServiceKafkaMirrorMakerDeleteReplicationFlow
  - ServiceKafkaMirrorMakerGetReplicationFlow
  - ServiceKafkaMirrorMakerGetReplicationFlows
  - ServiceKafkaMirrorMakerPatchReplicationFlow
KafkaSchemaRegistry:
  - ServiceSchemaRegistryAclAdd
  - ServiceSchemaRegistryAclDelete
  - ServiceSchemaRegistryAclList
  - ServiceSchemaRegistryCompatibility
  - ServiceSchemaRegistryGlobalConfigGet
  - ServiceSchemaRegistryGlobalConfigPut
  - ServiceSchemaRegistrySchemaGet
  - ServiceSchemaRegistrySubjectConfigGet
  - ServiceSchemaRegistrySubjectConfigPut
  - ServiceSchemaRegistrySubjectDelete
  - ServiceSchemaRegistrySubjectVersionDelete
  - ServiceSchemaRegistrySubjectVersionGet
  - ServiceSchemaRegistrySubjectVersionPost
  - ServiceSchemaRegistrySubjectVersionSchemaGet
  - ServiceSchemaRegistrySubjectVersionsGet
  - ServiceSchemaRegistrySubjects
KafkaTopic:
  - ServiceKafkaTopicCreate
  - ServiceKafkaTopicDelete
  - ServiceKafkaTopicGet
  - ServiceKafkaTopicList
  - ServiceKafkaTopicMessageList
  - ServiceKafkaTopicMessageProduce
  - ServiceKafkaTopicUpdate
MySQL:
  - MySQLServiceQueryStatistics
OpenSearch:
  - ServiceOpenSearchAclGet
  - ServiceOpenSearchAclSet
  - ServiceOpenSearchAclUpdate
  - ServiceOpenSearchIndexDelete
  - ServiceOpenSearchIndexList
  - ServiceOpenSearchSecurityGet
  - ServiceOpenSearchSecurityReset
  - ServiceOpenSearchSecuritySet
Organization:
  - OrganizationAuthDomainLink
  - OrganizationAuthDomainList
  - OrganizationAuthDomainUnlink
  - OrganizationAuthenticationConfigGet
  - OrganizationAuthenticationConfigUpdate
  - OrganizationGet
  - OrganizationUpdate
  - PermissionsGet
  - PermissionsUpdate
  - UserOrganizationCreate
  - UserOrganizationsList
OrganizationUser:
  - OrganizationUserAuthenticationMethodsList
  - OrganizationUserDelete
  - OrganizationUserGet
  - OrganizationUserInvitationAccept
  - OrganizationUserInvitationDelete
  - OrganizationUserInvitationsList
  - OrganizationUserInvite
  - OrganizationUserList
  - OrganizationUserPasswordReset
  - OrganizationUserRevokeToken
  - OrganizationUserTokensList
  - OrganizationUserUpdate
PostgreSQL:
  - PGServiceAvailableExtensions
  - PGServiceQueryStatistics
  - PgAvailableExtensions
  - ServicePGBouncerCreate
  - ServicePGBouncerDelete
  - ServicePGBouncerUpdate
Privatelink:
  - PublicPrivatelinkAvailabilityList
  - ServicePrivatelinkAWSConnectionList
  - ServicePrivatelinkAWSCreate
  - ServicePrivatelinkAWSDelete
  - ServicePrivatelinkAWSGet
  - ServicePrivatelinkAWSUpdate
  - ServicePrivatelinkAzureConnectionApproval
  - ServicePrivatelinkAzureConnectionList
  - ServicePrivatelinkAzureConnectionUpdate
  - ServicePrivatelinkAzureCreate
  - ServicePrivatelinkAzureDelete
  - ServicePrivatelinkAzureGet
  - ServicePrivatelinkAzureUpdate
Project:
  - ListProjectVpcPeeringConnectionTypes
  - ProjectAlertsList
  - ProjectCreate
  - ProjectDelete
  - ProjectDownloadSBOMReport
  - ProjectGenerateSbomDownloadUrl
  - ProjectGet
  - ProjectGetEventLogs
  - ProjectInvite
  - ProjectInviteAccept
  - ProjectInviteDelete
  - ProjectKmsGetCA
  - ProjectList
  - ProjectPrivatelinkAvailabilityList
  - ProjectServicePlanList
  - ProjectServicePlanPriceGet
  - ProjectServicePlanSpecsGet
  - ProjectServiceTypesGet
  - ProjectServiceTypesList
  - ProjectTagsList
  - ProjectTagsReplace
  - ProjectTagsUpdate
  - ProjectUpdate
  - ProjectUserList
  - ProjectUserRemove
  - ProjectUserUpdate
ProjectBilling:
  - InvoiceGet
  - ProjectCreditsClaim
  - ProjectCreditsList
  - ProjectInvoiceGet
  - ProjectInvoiceList
Service:
  - ListProjectServiceTypes
  - ListPublicServiceTypes
  - ListServiceVersions
  - ProjectGetServiceLogs
  - ProjectServiceTagsList
  - ProjectServiceTagsReplace
  - ProjectServiceTagsUpdate
  - ServiceAlertsList
  - ServiceBackupToAnotherRegionReport
  - ServiceBackupsGet
  - ServiceCancelQuery
  - ServiceCreate
  - ServiceDatabaseCreate
  - ServiceDatabaseDelete
  - ServiceDatabaseList
  - ServiceDelete
  - ServiceEnableWrites
  - ServiceGet
  - ServiceGetMigrationStatus
  - ServiceInfluxDBStats
  - ServiceIntegrationCreate
  - ServiceIntegrationDelete
  - ServiceIntegrationEndpointCreate
  - ServiceIntegrationEndpointDelete
  - ServiceIntegrationEndpointGet
  - ServiceIntegrationEndpointList
  - ServiceIntegrationEndpointTypes
  - ServiceIntegrationEndpointUpdate
  - ServiceIntegrationGet
  - ServiceIntegrationList
  - ServiceIntegrationTypes
  - ServiceIntegrationUpdate
  - ServiceKmsGetCA
  - ServiceKmsGetKeypair
  - ServiceList
  - ServiceMaintenanceStart
  - ServiceMetricsFetch
  - ServiceQueryActivity
  - ServiceQueryStatisticsReset
  - ServiceTaskCreate
  - ServiceTaskGet
  - ServiceUpdate
  - ServiceUserCreate
  - ServiceUserCredentialsModify
  - ServiceUserCredentialsReset
  - ServiceUserDelete
  - ServiceUserGet
StaticIP:
  - ProjectStaticIPAssociate
  - ProjectStaticIPAvailabilityList
  - ProjectStaticIPDissociate
  - ProjectStaticIPPatch
  - PublicStaticIPAvailabilityList
  - StaticIPCreate
  - StaticIPList
Thanos:
  - ServiceThanosStorageSummary
User:
  - AccessTokenCreate
  - AccessTokenList
  - AccessTokenRevoke
  - AccessTokenUpdate
  - CheckPasswordStrengthExistingUser
  - CheckPasswordStrengthNewUser
  - OrganizationMemberGroupsList
  - TwoFactorAuthConfigure
  - TwoFactorAuthConfigureOTP
  - UserAccountDelete
  - UserAccountInvitesAccept
  - UserAccountInvitesList
  - UserAuth
  - UserAuthLoginOptions
  - UserAuthenticationMethodDelete
  - UserAuthenticationMethodsList
  - UserCreate
  - UserExpireTokens
  - UserInfo
  - UserLogout
  - UserPasswordChange
  - UserPasswordReset
  - UserPasswordResetRequest
  - UserUpdate
  - UserVerifyEmail
  - ValidateCreditCode
  - ValidateReferralCode
UserGroup:
  - UserGroupCreate
  - UserGroupDelete
  - UserGroupGet
  - UserGroupMemberList
  - UserGroupMembersUpdate
  - UserGroupUpdate
  - UserGroupsList
Vpc:
  - VpcCreate
  - VpcDelete
  - VpcGet
  - VpcList
  - VpcPeeringConnectionCreate
  - VpcPeeringConnectionDelete
  - VpcPeeringConnectionUpdate
  - VpcPeeringConnectionWithRegionDelete
  - VpcPeeringConnectionWithResourceGroupDelete
